### PR TITLE
Add database tests

### PR DESCRIPTION
**Pull request by greena13**
- Refactor database tests for an approach that more resembles unit tests
- Add tests for ref (on(), off(), once(), set(), update(), remove() methods)
- Cleans up TestSuite.js, a little

Disclaimers:
- Still have to add tests for list and query methods 
- Uses `sinon` (because the project already uses should.js, which has a nice integration, `should-sinon`, to work with `sinon`). I've had to depend on a fork of sinon while I wait for bugfix to be merged into sinon. If it doesn't happen for whatever reason, sinon should be swapped out for another JS spy library that's compatible with React Native.

### CODE REVIEW

**Comment by Salakar** [comment]
Definitely much cleaner, thanks for this. Will fully check over it in the morning.

Original test app was a bit of a rush job so I could focus on the actual lib, so it definitely needed some love =]

Some of the tests I did need to run in the order they're created, e.g storage ones, I think it may be worth dropping promise.map and concurrency and stick to a standard 1 at a time promise for each like most testing frameworks, otherwise i feel concurrent tests will cause issues in the long run, thoughts?

**Comment by greena13** [comment]
Agreed. A simpler, more deterministic test suite is better. 

I guess we could add concurrency back if the run time for the test suite starts to get ridiculous. I'll start to remove it and update this pull request.

**Comment by Salakar** [comment]
Shouldn't get too bad to be honest, each suite/test is targetable as runnable on their own for specific tests anyway.

Am working on transaction support at the moment for database, so give me a shout when you feel comfortable this is ready for merging and i'll merge. You're also welcome to commit rights on here if you want it?

**Comment by greena13** [comment]
Commit rights may save some time.

**Comment by Salakar** [comment]
Added you as a collaborator: https://github.com/invertase/react-native-firebase-tests/invitations

**Pull request merged**
